//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCV.IILSC.Web.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WarehouseOperationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarehouseOperationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCV.IILSC.Web.Content.Resources.WarehouseOperationsResources", typeof(WarehouseOperationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K dispozici.
        /// </summary>
        public static string AvailableQuantity {
            get {
                return ResourceManager.GetString("AvailableQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Základní informace.
        /// </summary>
        public static string BasicInformations {
            get {
                return ResourceManager.GetString("BasicInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalogové číslo.
        /// </summary>
        public static string CatalogNumber {
            get {
                return ResourceManager.GetString("CatalogNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat.č..
        /// </summary>
        public static string CatalogueNo {
            get {
                return ResourceManager.GetString("CatalogueNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihrádka.
        /// </summary>
        public static string Compartment {
            get {
                return ResourceManager.GetString("Compartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vytvoření.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořil.
        /// </summary>
        public static string CreatedUser {
            get {
                return ResourceManager.GetString("CreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořeno.
        /// </summary>
        public static string CreatedWarehouseOperation {
            get {
                return ResourceManager.GetString("CreatedWarehouseOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuální stav.
        /// </summary>
        public static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit.
        /// </summary>
        public static string DeleteOperation {
            get {
                return ResourceManager.GetString("DeleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdíl.
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo dokladu.
        /// </summary>
        public static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neobsahuje žádný záznam.
        /// </summary>
        public static string DoesNotContainAnyRecord {
            get {
                return ResourceManager.GetString("DoesNotContainAnyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadané číslo dokumentu již existuje.
        /// </summary>
        public static string EnteredDocumentNumberAlreadyExists {
            get {
                return ResourceManager.GetString("EnteredDocumentNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zadejte množství.
        /// </summary>
        public static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportovat do .PDF.
        /// </summary>
        public static string ExportToPdf {
            get {
                return ResourceManager.GetString("ExportToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hledat zboží.
        /// </summary>
        public static string FindWare {
            get {
                return ResourceManager.GetString("FindWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokončeno.
        /// </summary>
        public static string FinishedWarehouseOperation {
            get {
                return ResourceManager.GetString("FinishedWarehouseOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaskladnění dokončeno.
        /// </summary>
        public static string IncomeCompleted {
            get {
                return ResourceManager.GetString("IncomeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaskladněné položky.
        /// </summary>
        public static string IncomedItems {
            get {
                return ResourceManager.GetString("IncomedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Průběh zaskladnění.
        /// </summary>
        public static string IncomeProgress {
            get {
                return ResourceManager.GetString("IncomeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpracováno.
        /// </summary>
        public static string InProgressWarehouseOperation {
            get {
                return ResourceManager.GetString("InProgressWarehouseOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte kladné množství zboží.
        /// </summary>
        public static string InputPositiveQuantityOfWare {
            get {
                return ResourceManager.GetString("InputPositiveQuantityOfWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte zboží k zaskladnění..
        /// </summary>
        public static string InputWareForIncome {
            get {
                return ResourceManager.GetString("InputWareForIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte zboží k vyskladnění..
        /// </summary>
        public static string InputWareForOutcome {
            get {
                return ResourceManager.GetString("InputWareForOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední skladové operace.
        /// </summary>
        public static string LatestWarehouseOperations {
            get {
                return ResourceManager.GetString("LatestWarehouseOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesunuté položky.
        /// </summary>
        public static string MovedItems {
            get {
                return ResourceManager.GetString("MovedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesun dokončen.
        /// </summary>
        public static string MoveFinished {
            get {
                return ResourceManager.GetString("MoveFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Průběh přesunu.
        /// </summary>
        public static string MoveProgress {
            get {
                return ResourceManager.GetString("MoveProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové zaskladnění.
        /// </summary>
        public static string NewIncome {
            get {
                return ResourceManager.GetString("NewIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové vyskladnění.
        /// </summary>
        public static string NewOutcome {
            get {
                return ResourceManager.GetString("NewOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový přesun.
        /// </summary>
        public static string NewWareMove {
            get {
                return ResourceManager.GetString("NewWareMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Další rozpracované operace.
        /// </summary>
        public static string NextUnfinishedOperation {
            get {
                return ResourceManager.GetString("NextUnfinishedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyla nalezena žádná skladová operace.
        /// </summary>
        public static string NoOperationWasFound {
            get {
                return ResourceManager.GetString("NoOperationWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyl nalezen žádný záznam.
        /// </summary>
        public static string NoRecordWasFound {
            get {
                return ResourceManager.GetString("NoRecordWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyskladnění.
        /// </summary>
        public static string Outcome {
            get {
                return ResourceManager.GetString("Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyskladnění dokončeno.
        /// </summary>
        public static string OutcomeCompleted {
            get {
                return ResourceManager.GetString("OutcomeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyskladněné položky.
        /// </summary>
        public static string OutcomedItems {
            get {
                return ResourceManager.GetString("OutcomedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Průběh vyskladnění.
        /// </summary>
        public static string OutcomeProgress {
            get {
                return ResourceManager.GetString("OutcomeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povoleny jsou pouze číselné hodnoty..
        /// </summary>
        public static string PleaseEnterValidNumber {
            get {
                return ResourceManager.GetString("PleaseEnterValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesun.
        /// </summary>
        public static string Presun {
            get {
                return ResourceManager.GetString("Presun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaskladnění.
        /// </summary>
        public static string Prijem {
            get {
                return ResourceManager.GetString("Prijem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpracoval.
        /// </summary>
        public static string ProcessedUser {
            get {
                return ResourceManager.GetString("ProcessedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpracováno.
        /// </summary>
        public static string ProcessingDate {
            get {
                return ResourceManager.GetString("ProcessingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Množství.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Množství opravdu.
        /// </summary>
        public static string QuantityReal {
            get {
                return ResourceManager.GetString("QuantityReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Množství systém.
        /// </summary>
        public static string QuantitySystem {
            get {
                return ResourceManager.GetString("QuantitySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výsledek hledání.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledat zásobu.
        /// </summary>
        public static string SearchStock {
            get {
                return ResourceManager.GetString("SearchStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrat.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vybrat přihrádku.
        /// </summary>
        public static string SelectCompartment {
            get {
                return ResourceManager.GetString("SelectCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * zvolte regál k zaskladnění.
        /// </summary>
        public static string SelectRackForIncome {
            get {
                return ResourceManager.GetString("SelectRackForIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * zvolte zboží.
        /// </summary>
        public static string SelectWare {
            get {
                return ResourceManager.GetString("SelectWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * zvolte zboží k zaskladnění.
        /// </summary>
        public static string SelectWareForIncome {
            get {
                return ResourceManager.GetString("SelectWareForIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * zvolte zboží k vyskladnění.
        /// </summary>
        public static string SelectWareForOutcome {
            get {
                return ResourceManager.GetString("SelectWareForOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krok 1.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krok 2.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krok 3.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventura.
        /// </summary>
        public static string Stocktaking {
            get {
                return ResourceManager.GetString("Stocktaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nástroje.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpracované operace .
        /// </summary>
        public static string UnfinishedOperation {
            get {
                return ResourceManager.GetString("UnfinishedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpracované skladové operace.
        /// </summary>
        public static string UnfinishedWareHouseOperation {
            get {
                return ResourceManager.GetString("UnfinishedWareHouseOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednotka.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zboží.
        /// </summary>
        public static string Ware {
            get {
                return ResourceManager.GetString("Ware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladovací objekt.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaskladnění zboží.
        /// </summary>
        public static string WareIncome {
            get {
                return ResourceManager.GetString("WareIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesun zboží.
        /// </summary>
        public static string WareMove {
            get {
                return ResourceManager.GetString("WareMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název zboží.
        /// </summary>
        public static string WareName {
            get {
                return ResourceManager.GetString("WareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyskladnění zboží.
        /// </summary>
        public static string WareOutcome {
            get {
                return ResourceManager.GetString("WareOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyskladnit zboží.
        /// </summary>
        public static string WareOutcomeVerb {
            get {
                return ResourceManager.GetString("WareOutcomeVerb", resourceCulture);
            }
        }
    }
}
